services:
  db:
    image: postgres:15-alpine
    container_name: trocadin-db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 12345fny
      POSTGRES_DB: trocadindb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: